{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "750c9f94",
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n",
      "PyTables version:    3.6.1\n",
      "HDF5 version:        1.12.1\n",
      "NumPy version:       1.21.4\n",
      "Numexpr version:     2.8.1 (not using Intel's VML/MKL)\n",
      "Zlib version:        1.2.11 (in Python interpreter)\n",
      "BZIP2 version:       1.0.8 (13-Jul-2019)\n",
      "Blosc version:       1.21.0 (2020-12-22)\n",
      "Blosc compressors:   blosclz (2.3.0), lz4 (1.9.3), lz4hc (1.9.3), zlib (1.2.8), zstd (1.4.8)\n",
      "Blosc filters:       shuffle, bitshuffle\n",
      "Python version:      3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]\n",
      "Platform:            Windows-10-10.0.19044-SP0\n",
      "Byte-ordering:       little\n",
      "Detected cores:      8\n",
      "Default encoding:    utf-8\n",
      "Default FS encoding: utf-8\n",
      "Default locale:      (de_DE, cp1252)\n",
      "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n",
      "Performing only a light (yet comprehensive) subset of the test suite.\n",
      "If you want a more complete test, try passing the --heavy flag to this script\n",
      "(or set the 'heavy' parameter in case you are using tables.test() call).\n",
      "The whole suite will take more than 4 hours to complete on a relatively\n",
      "modern CPU and around 512 MB of main memory.\n",
      "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\filters.py:326: FiltersWarning: compression library ``lzo`` is not available; using ``zlib`` instead\n",
      "  warnings.warn(\"compression library ``%s`` is not available; \"\n",
      "C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_array.py:519: FutureWarning: creating an array with a subarray dtype will behave differently when the `np.array()` (or `asarray`, etc.) call includes an array or array object.\n",
      "If you are converting a single array or a list of arrays,you can opt-in to the future behaviour using:\n",
      "    np.array(arr, dtype=np.dtype(['f', dtype]))['f']\n",
      "    np.array([arr1, arr2], dtype=np.dtype(['f', dtype]))['f']\n",
      "\n",
      "By including a new field and indexing it after the conversion.\n",
      "This may lead to a different result or to current failures succeeding.  (FutureWarning since NumPy 1.20)\n",
      "  tupleInt = numpy.array(numpy.arange((4)), dtype=(numpy.int_, (4,)))\n",
      "..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s............................................ssss...................................................ss.....................................................................................................sssss....F......................................C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\flavor.py:395: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.\n",
      "  nparr = numpy.array(array)\n",
      "..........................................................................................................................................................................................................................................................................................................................................................................................................................................ssssssssssssssssssssssssssss........................................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssss...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................ssssss..........................................................................................................................................................................................................................................................................................C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py:544: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.\n",
      "  key = numpy.array(key)\n",
      ".........................................................................................................................................................sssssss........................................................ssssssssssssss...................................................................................................................................................................................................ssssssssss............................................................sssss..........ssssssssss.................................................................ssssssssss..........ssssssssss...............................................................................................................................................................ssssss............ssssss.................................................................................................................................EEEEEEEEEEEE..................................................................s................................................................................................................................................................................................................................................................................................s...s........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................ssssssssssssssssssss.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\n",
      "======================================================================\n",
      "ERROR: test00_attributes (tables.tests.test_vlarray.Fletcher32TestCase)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test01_read (tables.tests.test_vlarray.Fletcher32TestCase)\n",
      "Checking vlarray read.\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test02a_getitem (tables.tests.test_vlarray.Fletcher32TestCase)\n",
      "Checking vlarray __getitem__ (slices)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test02b_getitem (tables.tests.test_vlarray.Fletcher32TestCase)\n",
      "Checking vlarray __getitem__ (scalars)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test03_append (tables.tests.test_vlarray.Fletcher32TestCase)\n",
      "Checking vlarray append.\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test04_get_row_size (tables.tests.test_vlarray.Fletcher32TestCase)\n",
      "Checking get_row_size method.\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test00_attributes (tables.tests.test_vlarray.AllFiltersTestCase)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test01_read (tables.tests.test_vlarray.AllFiltersTestCase)\n",
      "Checking vlarray read.\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test02a_getitem (tables.tests.test_vlarray.AllFiltersTestCase)\n",
      "Checking vlarray __getitem__ (slices)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test02b_getitem (tables.tests.test_vlarray.AllFiltersTestCase)\n",
      "Checking vlarray __getitem__ (scalars)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test03_append (tables.tests.test_vlarray.AllFiltersTestCase)\n",
      "Checking vlarray append.\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "ERROR: test04_get_row_size (tables.tests.test_vlarray.AllFiltersTestCase)\n",
      "Checking get_row_size method.\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 37, in setUp\n",
      "    self.populateFile()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\tests\\test_vlarray.py\", line 47, in populateFile\n",
      "    vlarray = self.h5file.create_vlarray(group, 'vlarray1',\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\file.py\", line 1493, in create_vlarray\n",
      "    ptobj = VLArray(parentnode, name,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 349, in __init__\n",
      "    super(VLArray, self).__init__(parentnode, name, new, filters,\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\leaf.py\", line 286, in __init__\n",
      "    super(Leaf, self).__init__(parentnode, name, _log)\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\node.py\", line 264, in __init__\n",
      "    self._v_objectid = self._g_create()\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\vlarray.py\", line 419, in _g_create\n",
      "    self._v_objectid = self._create_array(self._v_new_title)\n",
      "  File \"tables\\hdf5extension.pyx\", line 1968, in tables.hdf5extension.VLArray._create_array\n",
      "tables.exceptions.HDF5ExtError: HDF5 error back trace\n",
      "\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5D.c\", line 141, in H5Dcreate2\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1806, in H5VL_dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLcallback.c\", line 1771, in H5VL__dataset_create\n",
      "    dataset create failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5VLnative_dataset.c\", line 73, in H5VL__native_dataset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 396, in H5D__create_named\n",
      "    unable to create and link to dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1767, in H5L_link_object\n",
      "    unable to create new link to object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 2009, in H5L__create_real\n",
      "    can't insert link\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 837, in H5G_traverse\n",
      "    internal path traversal failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Gtraverse.c\", line 613, in H5G__traverse_real\n",
      "    traversal operator failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5L.c\", line 1815, in H5L__link_cb\n",
      "    unable to create object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Oint.c\", line 2468, in H5O_obj_create\n",
      "    unable to open object\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Doh.c\", line 289, in H5O__dset_create\n",
      "    unable to create dataset\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Dint.c\", line 1282, in H5D__create\n",
      "    H5Z_has_optional_filter() failed\n",
      "  File \"D:\\bld\\hdf5_split_1638790631866\\work\\src\\H5Z.c\", line 1044, in H5Z_ignore_filters\n",
      "    not suitable for filters\n",
      "\n",
      "End of HDF5 error back trace\n",
      "\n",
      "Problems creating the VLArray.\n",
      "\n",
      "======================================================================\n",
      "FAIL: from_sctype (tables.atom.Atom)\n",
      "Doctest: tables.atom.Atom.from_sctype\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\doctest.py\", line 2204, in runTest\n",
      "    raise self.failureException(self.format_failure(new.getvalue()))\n",
      "AssertionError: Failed doctest test for tables.atom.Atom.from_sctype\n",
      "  File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\atom.py\", line 326, in from_sctype\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\atom.py\", line 341, in tables.atom.Atom.from_sctype\n",
      "Failed example:\n",
      "    Atom.from_sctype('Float64')\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\doctest.py\", line 1336, in __run\n",
      "        exec(compile(example.source, filename, \"single\",\n",
      "      File \"<doctest tables.atom.Atom.from_sctype[3]>\", line 1, in <module>\n",
      "        Atom.from_sctype('Float64')\n",
      "      File \"C:\\Users\\Christian\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\tables\\atom.py\", line 348, in from_sctype\n",
      "        raise ValueError(\"unknown NumPy scalar type: %r\" % (sctype,))\n",
      "    ValueError: unknown NumPy scalar type: 'Float64'\n",
      "\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 6358 tests in 419.356s\n",
      "\n",
      "FAILED (failures=1, errors=12, skipped=203)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "1"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import tables\n",
    "tables.test()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a3be82dd",
   "metadata": {},
   "outputs": [
    {
     "ename": "MemoryError",
     "evalue": "Unable to allocate 74.5 GiB for an array with shape (10000000000,) and data type int64",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mMemoryError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[1;32mC:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_13000/3545416677.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mtables\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m \u001b[0ma\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mrand\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m100000\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;36m100000\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mformat\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'csr'\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;31m#imagine that many values are stored in this matrix and that sparsity is low\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      5\u001b[0m \u001b[0mb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0ma\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mT\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[0ml\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mm\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mn\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0ma\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshape\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0ma\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshape\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mb\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshape\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\scipy\\sparse\\construct.py\u001b[0m in \u001b[0;36mrand\u001b[1;34m(m, n, density, format, dtype, random_state)\u001b[0m\n\u001b[0;32m    866\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    867\u001b[0m     \"\"\"\n\u001b[1;32m--> 868\u001b[1;33m     \u001b[1;32mreturn\u001b[0m \u001b[0mrandom\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mm\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdensity\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mformat\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrandom_state\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\Documents\\coding\\anaconda3\\envs\\coins\\lib\\site-packages\\scipy\\sparse\\construct.py\u001b[0m in \u001b[0;36mrandom\u001b[1;34m(m, n, density, format, dtype, random_state, data_rvs)\u001b[0m\n\u001b[0;32m    806\u001b[0m             \u001b[0mdata_rvs\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mpartial\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrandom_state\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0muniform\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m0.\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m1.\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    807\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 808\u001b[1;33m     \u001b[0mind\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mrandom_state\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mchoice\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msize\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mk\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mreplace\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    809\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    810\u001b[0m     \u001b[0mj\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mnp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfloor\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mind\u001b[0m \u001b[1;33m*\u001b[0m \u001b[1;36m1.\u001b[0m \u001b[1;33m/\u001b[0m \u001b[0mm\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mastype\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtp\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mcopy\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mmtrand.pyx\u001b[0m in \u001b[0;36mnumpy.random.mtrand.RandomState.choice\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;32mmtrand.pyx\u001b[0m in \u001b[0;36mnumpy.random.mtrand.RandomState.permutation\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mMemoryError\u001b[0m: Unable to allocate 74.5 GiB for an array with shape (10000000000,) and data type int64"
     ]
    }
   ],
   "source": [
    "from scipy.sparse import csr_matrix, rand\n",
    "import tables as tb\n",
    "\n",
    "a = rand(100000,100000, format='csr') #imagine that many values are stored in this matrix and that sparsity is low\n",
    "b = a.T\n",
    "l, m, n = a.shape[0], a.shape[1], b.shape[1]\n",
    " \n",
    "f = tb.open_file('dot.h5', 'w')\n",
    "filters = tb.Filters(complevel=5, complib='blosc')\n",
    "out = f.create_carray(f.root, 'data', tb.Float32Atom(), shape=(l, n), filters=filters)\n",
    " \n",
    "bl = 1000 #this is the number of rows we calculate each loop\n",
    "#this may not the most efficient value\n",
    "#look into buffersize usage in PyTables and adopt the buffersite of the\n",
    "#carray accordingly to improve specifically fetching performance\n",
    " \n",
    "b = b.tocsc() #we slice b on columns, csc improves performance\n",
    " \n",
    "#this can also be changed to slice on rows instead of columns\n",
    "for i in range(0, l, bl):\n",
    "  out[:,i:min(i+bl, l)] = (a.dot(b[:,i:min(i+bl, l)])).toarray()\n",
    " \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "eaf994db",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<closed File>"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "f"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "454ad71e",
   "metadata": {},
   "outputs": [],
   "source": [
    "f.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "47de779b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "File(filename=tutorial1.h5, title='Test file', mode='w', root_uep='/', filters=Filters(complevel=0, shuffle=False, bitshuffle=False, fletcher32=False, least_significant_digit=None))\n",
       "/ (RootGroup) 'Test file'"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from tables import *\n",
    "\n",
    "h5file = open_file(\"tutorial1.h5\", mode=\"w\", title=\"Test file\")\n",
    "\n",
    "h5file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "26f4eb99",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
